export const POST_CONSTRUCTOR_ITEMS_REQUEST = 'POST_CONSTRUCTOR_ITEMS_REQUEST';
export const POST_CONSTRUCTOR_ITEMS_SUCCESS = 'POST_CONSTRUCTOR_ITEMS_SUCCESS';
export const POST_CONSTRUCTOR_ITEMS_FAILED = 'POST_CONSTRUCTOR_ITEMS_FAILED';
export const RESET_ORDER_NUMBER = 'RESET_ORDER_NUMBER';

export function closePopup() {
	return {
		type: RESET_ORDER_NUMBER,
	};
}

