export const SET_INFO_CHOSEN_INGREDIENT: 'SET_INFO_CHOSEN_INGREDIENT' = 'SET_INFO_CHOSEN_INGREDIENT';
export const DELETE_INFO_CHOSEN_INGREDIENT: 'DELETE_INFO_CHOSEN_INGREDIENT' = 'DELETE_INFO_CHOSEN_INGREDIENT';
