export const GET_API_ITEMS_REQUEST: 'GET_API_ITEMS_REQUEST' = 'GET_API_ITEMS_REQUEST';
export const GET_API_ITEMS_SUCCESS: 'GET_API_ITEMS_SUCCESS' = 'GET_API_ITEMS_SUCCESS';
export const GET_API_ITEMS_FAILED: 'GET_API_ITEMS_FAILED' = 'GET_API_ITEMS_FAILED';